quarkus.http.non-application-root-path=/

quarkus.log.console.enable=true
quarkus.log.console.level=INFO
quarkus.log.console.color=true
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{1.}] (%t) %s%e%n

quarkus.native.resources.includes=META-INF/resources/**,com/google/javascript/jscomp/**

quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST
quarkus.http.cors.headers=Content-Type,Accept

quarkus.micrometer.binder.jvm=false

server.download-file-max-size=${MAX_DOWNLOAD_FILE_SIZE:1048576}
server.download-urls-pre-request=${MAX_DOWNLOAD_URLS_PER_REQUEST:10}
server.cache-max-size = ${MAX_CACHE_DIR_SIZE:1073741824}
server.cache-location=${CACHE_DIR:cache}
server.unique-key-length = ${UNIQUE_KEY_LENGTH:8}

quarkus.http.limits.max-body-size=${server.download-file-max-size}

quarkus.datasource.db-kind=postgresql

quarkus.datasource.reactive.url=postgresql://localhost:5432/jscompressor
quarkus.datasource.reactive.username=postgres
quarkus.datasource.reactive.password=postgres

%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.hibernate-orm.sql-load-script=import.sql


%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.hibernate-orm.sql-load-script=import.sql


quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true
quarkus.hibernate-orm.log.highlight-sql=true
quarkus.hibernate-orm.log.jdbc-warnings=true