####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode.
#
# Before building the container image run:
#
# mvn package -Pnative
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.native -t quarkus/jscompressor .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/jscompressor
#
###
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.8@sha256:8ebe2ad8fdf3cab3e5a53c1edc69194c98209cfadab24b884f4ad9ebcf7bbbfc

WORKDIR /work
RUN microdnf update -y \
    && microdnf clean all \
    && mkdir -p /volume \
    && chown 1001:root /volume \
    && chmod "g+rwX" /volume
COPY --chown=1001:root target/*-runner /work/application

EXPOSE 8080
USER 1001

ENV CACHE_DIR=/volume

VOLUME /volume

ENTRYPOINT ["/work/application", "-Dquarkus.http.host=0.0.0.0"]
